### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Astricaelus** [Fedoraer/luogugu#10]
@Fedoraer [我觉得你最好小心一点儿。。。。](https://baike.baidu.com/item/%E7%A0%B4%E5%9D%8F%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%BF%A1%E6%81%AF%E7%B3%BB%E7%BB%9F%E7%BD%AA) ![tmp1ca99b2185dacfe98.png](https://www.z4a.net/images/2018/08/20/tmp1ca99b2185dacfe98.png)

**Comment by Lhcfl** [comment]
前排。。
小黑屋和洛谷日报让他出名了？

**Comment by Lonecharm-River** [comment]
Trying to fight with the laws is tring to find death. If he just want to be famous, he will expect so much. He will become a shit to be remembered in our mind.
@Fedoraer Don't you think it is right? Shamed of you!
