### ISSUE TITLE
而且你对CodeVS的攻击足以被判刑！

### ISSUE THREAD

**Issue by erweiz** [Fedoraer/luogugu#17]
![image](https://camo.githubusercontent.com/5aaba253b73819f005ccaeb049e7e5a70e267c52/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323031382f30382f32302f746d7031636139396232313835646163666539382e706e67)

**Comment by starx237** [comment]
你们不要真把这人当回事，他的病毒充其量不过是小学生的恶搞，根本没有技术含量，卡不了洛谷。
