### ISSUE TITLE
放弃吧，我将指出你的病毒是毫无意义的。

### ISSUE THREAD

**Issue by starx237** [Fedoraer/luogugu#19]
RT.洛谷已经更新了评测系统，一切试图修改洛谷的评测文件的程序都没有任何意义。
你的程序根本就无法修改tmp文件夹，而且你的自动AC机也会被拦截，你的程序是在docker里跑的，没有权限访问任何文件。并且system函数一定无效，只需要添加编译指令屏蔽该函数并且禁用内联汇编，你的所有试图调用系统进程的操作都会失效。
你甚至无法访问网络和修改内存，这就是断了你剩下的唯一出路。访问或创建任何输入输出文件之外的文件。别指望能够通过对tmp文件的修改来卡洛谷。这一点全洛谷的大佬全都试过，没有一个成功的，连内核级别的操作都无法得逞，更别说你的那个毫无意义的简单程序。洛谷的安全技术不亚于360安全卫士，甚至比360安全卫士更加强大：因为你的程序纵使能够造成再大的破坏，你却没有权限访问任何输入输出以外的内存，别指望硬件破坏好编译时攻击，甚至父进程还有一个类似360安全卫士的进程来监视你的进程，一旦发生任何状况就会将你的进程终止，并且你的程序在云端docker内造成的任何影响都不会影响到父进程，权限和docker已将你的所有出路截断。洛谷评测机制作者本人都无法破解它的安全防护。
如果你真的对坑人感兴趣，就不要挑战洛谷这种网站，你应该在家里的电脑上使用system权限来远程Hack，自由自在地访问网络，而不是在极端的低权限中做一些没有意义的操作。如果你连这个都不会，你就不是当Hacker的料。
你可以卡掉codevs，却卡不掉洛谷，理由上面已经说得非常清楚了。

**Comment by starx237** [comment]
@Fedoraer 停手吧，洛谷不是你能卡掉的。我打那么多字只是想告诉你不要以为自己的一点恶搞能造成多大的效果，等你有了突破docker和权限的能力，再来大放狂言，不过我想那时可能已经有了比docker更加强大的防护方法了。删掉此贴只是自欺欺人，如果你还是继续做着你的Hacker梦，我也不拦你。

**Comment by ztz11** [comment]
只要希望他别记着luogu一辈子就行了，不然万一有些系统层级漏洞被他发现了就不好玩了（虽然99.99%他知道了也不会用）

**Comment by starx237** [comment]
@Fedoraer  别指望能够卡LuoguIDE，它已经被lin_toto更新过了。狂妄自大是你最大的弱点，你要是在一星期前卡洛谷，说不定能成功，你非要给洛谷那么长时间来更新技术，还在github大肆宣传。你这种作风必然会失败，从你卡洛谷这件事上就能看出你的愚昧。

**Comment by IGhorse** [comment]
Fe老哥想法不错，但是抱歉，一个合格的，能承担cf级评测的OJ必须趾高气昂，如果连哪有啦么多BUG的自信都没有，这样的OJ，如何信赖？没有人会和一种违反社会主义核心价值观的人冷静下来平等地探讨IT，对于错误，每个人都有批评的权利。从这点上来讲，所有LGuser没有理由不残酷，严肃地对待你。真诚地反馈BUGwill die？在你发现这类BUG时，你有机会成为帮助LG发展的功臣，但当你无理取闹甚至在github“嘲讽时”，抱歉，你就是一个只能用”哪来啦么多BUG？“回答的无理取闹者，甚至，小学生
