### ISSUE TITLE
触犯了Github 的TOS，了解一下

### ISSUE THREAD

**Issue by abc1763613206** [Fedoraer/luogugu#20]
You agree that you will not under any circumstances upload, post, host, or transmit any content that:  
is discriminatory or abusive toward any individual or group;  
While using GitHub, you agree that you will not under any circumstances:  
**harass, abuse, threaten, or incite violence towards any individual or group, including GitHub employees,  
 officers, and agents, or other GitHub Users;**

**Comment by Sunbread** [comment]
同意。我会设法举报。
