### ISSUE TITLE
Click here and you will know how stupid you are

### ISSUE THREAD

**Issue by code004Accepted** [Fedoraer/luogugu#22]

**Comment by luoguMicroelectronics** [comment]
而且您的英语太差了。

**Comment by charliezcj** [comment]
d

**Comment by shleodai** [comment]
你们两个谷粉...喷人无不无聊

**Comment by aisuneko** [comment]
Anyway... who knows what's his real purpose of writing this auto ac machine @Fedoraer

**Comment by tkp30** [comment]
请注意......让道法课代表来解释一下。
关于AutoAC这个破玩意，其行为涉嫌违反《中华人民共和国计算机信息系统管理条例》《中华人民共和国刑法》，使用者也可以判罪（而且还是重罪！）
