### ISSUE TITLE
删了

### ISSUE THREAD

**Issue by miaowuawa** [Fedoraer/luogugu#24]

**Comment by Mosklia** [comment]
@quqi2  我也需要，谢谢！邮箱：sparky_14145@outlook.com  
试着卡一下校内OJ

**Comment by sparrowhe** [comment]
https://github.com/Fedoraer/luogugu/commit/aa5b99f4f8d0b40cfe2f2947cf53d2e05e6d5d79

**Comment by FilaretKun** [comment]
@Sparky-14145 这个项目利用的是洛谷Bug在学校OJ可能用不了吧

**Comment by langonginc** [comment]
@FilaretKun 很有可能用不了，这个是针对洛谷（之前）的问题做的
