### ISSUE TITLE
朋友，你火了

### ISSUE THREAD

**Issue by lin-toto** [Fedoraer/luogugu#4]

**Comment by memset0** [comment]
233

**Comment by QAQAutoMaton** [comment]
朋友，你火了

**Comment by Mosklia** [comment]
朋友，你火了

**Comment by ghost** [comment]
You are 666

**Comment by FCBM71** [comment]
pupils these days are really smart

**Comment by Feather-Sea** [comment]
Luogu观光团

**Comment by Lonecharm-River** [comment]
没发现lin_toto早就发现了这个，站务版多言了，抱歉。同时也希望想卡luogu的人不要再做这种事了，一是浪费时间，二是毫无意义，损人不利己，造成严重损害的话甚至要受到法律制裁！请三思而后行！

**Comment by moesoha** [comment]
@Lonecharm-River 不，洛咕支持有能力的人卡评测并报告给开发组。反对的是利用卡评测的方法影响公众利益的。

**Comment by Lonecharm-River** [comment]
@moesoha 确实

**Comment by Windowsredstone** [comment]
可不可以把system函数源码找到并在源码修改成如下

int __cdecl system(char *忘了名字)
{
    printf("禁止使用system函数！");
    abort();
    exit(1);
    int __boom=8362813/0;
    //各种强制终止程序方法全试一次
    return -1;
}
还有，其他的比如说啥freopen，ofstream，ifstream，FILE*全部这么搞一遍

**Comment by lin-toto** [comment]
@Lonecharm-River 事实上之前有人发现了一些其他的问题并报告，现在那个人在开发组拿着薪水吃香喝辣的。

基本就是楼上soha的态度。如果只是卡一次来证明自己nb发现了漏洞我们也可以理解，但是反复地利用甚至公开就不好玩了。

所以不好意思，现在我们修了洞我们nb了，就轮到我们来玩了。

**Comment by Lonecharm-River** [comment]
2333
