### ISSUE TITLE
您英语老师的棺材板我快压不住了

### ISSUE THREAD

**Issue by Arcturus1350** [Fedoraer/luogugu#6]
语法错误太多……强烈谴责。
还有作为面包姐姐的迷妹，
强烈谴责你拼错面包

**Comment by moesoha** [comment]
```cpp
#define bao int
#define ke_ai 0

bao main(){
    return ke_ai;
}
```

**Comment by FCBM71** [comment]
forgive it , forgive a pig, please

**Comment by Lonecharm-River** [comment]
Your English is too bad to read by those who have learnt a little, yet you should use your mother language to describe what you said to make sure that we Chinese even the foreigners can understand.

**Comment by Astricaelus** [comment]
前排围观

**Comment by Lhcfl** [comment]
I think it's so...

**Comment by lky1925** [comment]
猪是可以被原谅英语不好的。
