### ISSUE TITLE
Stop trying to do that

### ISSUE THREAD

**Issue by Lonecharm-River** [Fedoraer/luogugu#9]
I don't know why you like to do so absurd a thing! Don't you know that you will bring so many troubles for us? Oh! Yes, you do know that. But you just want to do for fun!
Awake, You will never be successful forever! On the one hand, Luogu have already updated its machines, and you have no chance to attack it again! All of these are just what you think by yourself, dreamt in your mind! It's true that you have made some OJs crashed. But on the other hand, you will be caught by police, PUNISHED BY LAWS! So I ask you not to do that again, otherwise you will regret what you have done!
At last, I'd like to say that your English is SO BAD. Plaese don't use your rubbish English to write README! Okay? I think not just Chinese but the foreigners will FEEL SICK after seeing your README or other words you wrote in English! SHAMED OF YOU!

**Comment by Lhcfl** [comment]
Well, so why do you use English?
默默点开“把网页翻译成中文”...

**Comment by Lonecharm-River** [comment]
@Lhcfl 让他感受英文的洗礼（滑稽

**Comment by Lhcfl** [comment]
...
